=== Zeldak7/jku/2022w/infosys2/04/sales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:ns="http://www.cis.jku.at/IFS2/Ue4_sales" targetNamespace="http://www.cis.jku.at/IFS2/Ue4_sales"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<!-- type definitions -->
	
	<complexType name="customer_t">
		<sequence>
			<element name="name" type="string" />
			<element name="address" type="string" />
			<element name="city" type="string" />
			<element name="state" type="string" />
			<element name="zip" type="string" />
			<element name="area" type="string" />
			<element name="phone" type="string" />
			<element name="repid" type="positiveInteger" />
			<element name="creditlimit" type="positiveInteger" />
			<element name="comments" type="string" minOccurs="0" />
			
			<element name="ord" type="ns:order_t" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	
		<attribute name="custid" type="positiveInteger" use="required" />
	</complexType>
	
	<complexType name="order_t">
		<sequence>
			<element name="orderdate" type="string" />
			<element name="commplan" type="string" minOccurs="0" />
			<element name="shipdate" type="string" />
			<element name="total" type="string" />
			
			<element name="item" type="ns:item_t" maxOccurs="unbounded" />
		</sequence>
		
		<attribute name="ordid" type="positiveInteger" use="required" />
	</complexType>
	
	<complexType name="item_t">
		<sequence>
			<element name="product_ref">
				<complexType>
					<attribute name="ref" use="required" type="positiveInteger" />
				</complexType>
			</element>
		
			<element name="actualprice" type="decimal" />
			<element name="qty" type="positiveInteger" />
			<element name="itemtot" type="decimal" />
		</sequence>
		
		<attribute name="itemid" type="positiveInteger" use="required" />
	</complexType>
	
	<complexType name="product_t">
		<sequence>
			<element name="descrip" type="string" />

			<element name="price" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="stdprice" type="string" />
						<element name="minprice" type="string" />
						<element name="startdate" type="string" />
						<element name="enddate" type="string" minOccurs="0" />
					</sequence>
				</complexType>
			</element>
		</sequence>
		
		<attribute name="prodid" type="positiveInteger" use="required" />
	</complexType>
	
	<!-- implementation -->
		
	<element name="sales">
		<complexType>
			<sequence>
				<element name="customer" type="ns:customer_t" maxOccurs="unbounded" />
				
				<element name="product" type="ns:product_t" maxOccurs="unbounded" />
			</sequence>
		</complexType>

		<key name="customer_key">
			<selector xpath="ns:customer" />
			<field xpath="@custid" />
		</key>
		
		<key name="order_key">
			<selector xpath="ns:customer/ord" />
			<field xpath="@ordid" />
		</key>
		
		<key name="item_key">
			<selector xpath="ns:customer/ord/item" />
			<field xpath="@itemid" />
		</key>

		<key name="product_key">
			<selector xpath="ns:product" />
			<field xpath="@prodid" />
		</key>
		
		<keyref name="product_keyref" refer="ns:product_key">
			<selector xpath="ns:customer/ord/item/product_ref" />
			<field xpath="@ref" />
		</keyref>
	</element>
</schema>

=== Zeldak7/jku/2022w/infosys2/04/sales_with_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cis.jku.at/IFS2/Ue4_sales sales.xsd" xmlns="http://www.cis.jku.at/IFS2/Ue4_sales">
	<customer custid="100">
		<name>JOCKSPORTS</name>
		<address>345 VIEWRIDGE</address>
		<city>BELMONT</city>
		<state>CA</state>
		<zip>96711</zip>
		<area>415</area>
		<phone>598-6609</phone>
		<repid>7844</repid>
		<creditlimit>5000</creditlimit>
		<comments>Very friendly people to work with -- sales rep likes to be called Mike.</comments>
		<ord ordid="606">
			<orderdate>1986-07-14</orderdate>
			<commplan>A</commplan>
			<shipdate>1986-07-30</shipdate>
			<total>3.4</total>
			<item itemid="1">
				<product_ref ref="102130"/>
				<actualprice>3.4</actualprice>
				<qty>1</qty>
				<itemtot>3.4</itemtot>
			</item>
		</ord>
		<ord ordid="609">
			<orderdate>1986-08-01</orderdate>
			<commplan>B</commplan>
			<shipdate>1986-08-15</shipdate>
			<total>97.5</total>
			<item itemid="1">
				<product_ref ref="100861"/>
				<actualprice>35</actualprice>
				<qty>1</qty>
				<itemtot>35</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100870"/>
				<actualprice>2.5</actualprice>
				<qty>5</qty>
				<itemtot>12.5</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="100890"/>
				<actualprice>50</actualprice>
				<qty>1</qty>
				<itemtot>50</itemtot>
			</item>
		</ord>
		<ord ordid="620">
			<orderdate>1987-06-12</orderdate>
			<shipdate>1987-06-12</shipdate>
			<total>4450</total>
			<item itemid="1">
				<product_ref ref="100860"/>
				<actualprice>35</actualprice>
				<qty>10</qty>
				<itemtot>350</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="200376"/>
				<actualprice>2.4</actualprice>
				<qty>1000</qty>
				<itemtot>2400</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="102130"/>
				<actualprice>3.4</actualprice>
				<qty>500</qty>
				<itemtot>1700</itemtot>
			</item>
		</ord>
		<ord ordid="621">
			<orderdate>1987-06-15</orderdate>
			<commplan>A</commplan>
			<shipdate>1987-01-01</shipdate>
			<total>730</total>
			<item itemid="1">
				<product_ref ref="100861"/>
				<actualprice>45</actualprice>
				<qty>10</qty>
				<itemtot>450</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100870"/>
				<actualprice>2.8</actualprice>
				<qty>100</qty>
				<itemtot>280</itemtot>
			</item>
		</ord>
	</customer>
	<customer custid="101">
		<name>TKB SPORT SHOP</name>
		<address>490 BOLI RD.</address>
		<city>REDWOOD CITY</city>
		<state>CA</state>
		<zip>94061</zip>
		<area>415</area>
		<phone>368-1223</phone>
		<repid>7521</repid>
		<creditlimit>10000</creditlimit>
		<comments>Rep called 5/8 about change in order - contact shipping.</comments>
		<ord ordid="610">
			<orderdate>1987-01-07</orderdate>
			<commplan>A</commplan>
			<shipdate>1987-01-08</shipdate>
			<total>101.4</total>
			<item itemid="1">
				<product_ref ref="100860"/>
				<actualprice>35</actualprice>
				<qty>1</qty>
				<itemtot>35</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100870"/>
				<actualprice>2.8</actualprice>
				<qty>3</qty>
				<itemtot>8.4</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="100890"/>
				<actualprice>58</actualprice>
				<qty>1</qty>
				<itemtot>58</itemtot>
			</item>
		</ord>
	</customer>
	<customer custid="102">
		<name>VOLLYRITE</name>
		<address>9722 HAMILTON</address>
		<city>BURLINGAME</city>
		<state>CA</state>
		<zip>95133</zip>
		<area>415</area>
		<phone>644-3341</phone>
		<repid>7654</repid>
		<creditlimit>7000</creditlimit>
		<comments>Company doing heavy promotion beginning 10/89. Prepare for large orders during
 winter.</comments>
		<ord ordid="611">
			<orderdate>1987-01-11</orderdate>
			<commplan>B</commplan>
			<shipdate>1987-01-11</shipdate>
			<total>45</total>
			<item itemid="1">
				<product_ref ref="100861"/>
				<actualprice>45</actualprice>
				<qty>1</qty>
				<itemtot>45</itemtot>
			</item>
		</ord>
		<ord ordid="602">
			<orderdate>1986-06-05</orderdate>
			<commplan>B</commplan>
			<shipdate>1986-06-20</shipdate>
			<total>56</total>
			<item itemid="1">
				<product_ref ref="100870"/>
				<actualprice>2.8</actualprice>
				<qty>20</qty>
				<itemtot>56</itemtot>
			</item>
		</ord>
		<ord ordid="603">
			<orderdate>1986-06-05</orderdate>
			<shipdate>1986-06-05</shipdate>
			<total>224</total>
			<item itemid="2">
				<product_ref ref="100860"/>
				<actualprice>56</actualprice>
				<qty>4</qty>
				<itemtot>224</itemtot>
			</item>
		</ord>
		<ord ordid="614">
			<orderdate>1987-02-01</orderdate>
			<shipdate>1987-02-05</shipdate>
			<total>23940</total>
			<item itemid="1">
				<product_ref ref="100860"/>
				<actualprice>35</actualprice>
				<qty>444</qty>
				<itemtot>15540</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100870"/>
				<actualprice>2.8</actualprice>
				<qty>1000</qty>
				<itemtot>2800</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="100871"/>
				<actualprice>5.6</actualprice>
				<qty>1000</qty>
				<itemtot>5600</itemtot>
			</item>
		</ord>
		<ord ordid="618">
			<orderdate>1987-02-15</orderdate>
			<commplan>A</commplan>
			<shipdate>1987-06-06</shipdate>
			<total>3510.5</total>
			<item itemid="1">
				<product_ref ref="100860"/>
				<actualprice>35</actualprice>
				<qty>23</qty>
				<itemtot>805</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100861"/>
				<actualprice>45.11</actualprice>
				<qty>50</qty>
				<itemtot>2255.5</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="100870"/>
				<actualprice>45</actualprice>
				<qty>10</qty>
				<itemtot>450</itemtot>
			</item>
		</ord>
	</customer>
	<customer custid="103">
		<name>JUST TENNIS</name>
		<address>HILLVIEW MALL</address>
		<city>BURLINGAME</city>
		<state>CA</state>
		<zip>97544</zip>
		<area>415</area>
		<phone>677-9312</phone>
		<repid>7521</repid>
		<creditlimit>3000</creditlimit>
		<comments>Contact rep about new line of tennis rackets.</comments>
		<ord ordid="616">
			<orderdate>1987-02-03</orderdate>
			<shipdate>1987-02-10</shipdate>
			<total>764</total>
			<item itemid="1">
				<product_ref ref="100861"/>
				<actualprice>45</actualprice>
				<qty>10</qty>
				<itemtot>450</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100870"/>
				<actualprice>2.8</actualprice>
				<qty>50</qty>
				<itemtot>140</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="100890"/>
				<actualprice>58</actualprice>
				<qty>2</qty>
				<itemtot>116</itemtot>
			</item>
			<item itemid="4">
				<product_ref ref="102130"/>
				<actualprice>3.4</actualprice>
				<qty>10</qty>
				<itemtot>34</itemtot>
			</item>
			<item itemid="5">
				<product_ref ref="200376"/>
				<actualprice>2.4</actualprice>
				<qty>10</qty>
				<itemtot>24</itemtot>
			</item>
		</ord>
	</customer>
	<customer custid="104">
		<name>EVERY MOUNTAIN</name>
		<address>574 SURRY RD.</address>
		<city>CUPERTINO</city>
		<state>CA</state>
		<zip>93301</zip>
		<area>408</area>
		<phone>996-2323</phone>
		<repid>7499</repid>
		<creditlimit>10000</creditlimit>
		<comments>Customer with high market share (23%) due to aggressive advertising.</comments>
		<ord ordid="612">
			<orderdate>1987-01-15</orderdate>
			<commplan>C</commplan>
			<shipdate>1987-01-20</shipdate>
			<total>5860</total>
			<item itemid="1">
				<product_ref ref="100860"/>
				<actualprice>30</actualprice>
				<qty>100</qty>
				<itemtot>3000</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100861"/>
				<actualprice>40.5</actualprice>
				<qty>20</qty>
				<itemtot>810</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="101863"/>
				<actualprice>10</actualprice>
				<qty>150</qty>
				<itemtot>1500</itemtot>
			</item>
			<item itemid="4">
				<product_ref ref="100871"/>
				<actualprice>5.5</actualprice>
				<qty>100</qty>
				<itemtot>550</itemtot>
			</item>
		</ord>
		<ord ordid="607">
			<orderdate>1986-07-18</orderdate>
			<commplan>C</commplan>
			<shipdate>1986-07-18</shipdate>
			<total>5.6</total>
			<item itemid="1">
				<product_ref ref="100871"/>
				<actualprice>5.6</actualprice>
				<qty>1</qty>
				<itemtot>5.6</itemtot>
			</item>
		</ord>
		<ord ordid="608">
			<orderdate>1986-07-25</orderdate>
			<commplan>C</commplan>
			<shipdate>1986-07-25</shipdate>
			<total>35.2</total>
			<item itemid="1">
				<product_ref ref="101860"/>
				<actualprice>24</actualprice>
				<qty>1</qty>
				<itemtot>24</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="100871"/>
				<actualprice>5.6</actualprice>
				<qty>2</qty>
				<itemtot>11.2</itemtot>
			</item>
		</ord>
		<ord ordid="619">
			<orderdate>1987-02-22</orderdate>
			<shipdate>1987-02-04</shipdate>
			<total>1260</total>
			<item itemid="1">
				<product_ref ref="200380"/>
				<actualprice>4</actualprice>
				<qty>100</qty>
				<itemtot>400</itemtot>
			</item>
			<item itemid="2">
				<product_ref ref="200376"/>
				<actualprice>2.4</actualprice>
				<qty>100</qty>
				<itemtot>240</itemtot>
			</item>
			<item itemid="3">
				<product_ref ref="102130"/>
				<actualprice>3.4</actualprice>
				<qty>100</qty>
				<itemtot>340</itemtot>
			</item>
			<item itemid="4">
				<product_ref ref="100871"/>
				<actualprice>5.6</actualprice>
				<qty>50</qty>
				<itemtot>280</itemtot>
			</item>
		</ord>
	</customer>
	<customer custid="105">
		<name>K + T SPORTS</name>
		<address>3476 EL PASEO</address>
		<city>SANTA CLARA</city>
		<state>CA</state>
		<zip>91003</zip>
		<area>408</area>
		<phone>376-9966</phone>
		<repid>7844</repid>
		<creditlimit>5000</creditlimit>
		<comments>Tends to order large amounts of merchandise at once. Accounting is considering
 raising their credit limit. Usually pays on time.</comments>
		<ord ordid="617">
			<orderdate>1987-02-05</orderdate>
			<shipdate>1987-06-03</shipdate>
			<total>46370</total>
			<item itemid="1">
